version: "3"
services:
  # APP
  app:
    image: jonathanbruno/thunder-web:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_USERNAME: pub_sub_user
      DATABASE_PASSWORD: pub_sub_password
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
    volumes:
      - ./:/var/www/app
  postgres:
    image: postgres:9.6.6
    environment:
      POSTGRES_DB: db_pub_sub
      POSTGRES_USER: pub_sub_user
      POSTGRES_PASSWORD: pub_sub_password
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data:cached"

volumes:
  db_data:

