default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: db_pub_sub
  username: pub_sub_user
  password: pub_sub_password
  host: postgres
  port: 5432
